"""replace_quantity_cases_with_extracted_size

Revision ID: 253b27de811a
Revises: 5fa6dc9a3d3d
Create Date: 2026-06-23 07:24:29.747847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '253b27de811a'
down_revision: Union[str, Sequence[str], None] = '5fa6dc9a3d3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tp_receipt_lines', sa.Column('extracted_size', sa.String(length=50), nullable=True))
    op.drop_column('tp_receipt_lines', 'quantity_cases')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tp_receipt_lines', sa.Column('quantity_cases', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('tp_receipt_lines', 'extracted_size')
    # ### end Alembic commands ###
