"""make_tp_nullable

Revision ID: 5fa6dc9a3d3d
Revises: e77e6142909d
Create Date: 2026-06-22 13:07:03.798811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fa6dc9a3d3d'
down_revision: Union[str, Sequence[str], None] = 'e77e6142909d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tp_receipts', 'tp_number',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('tp_receipts', 'supplier_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('tp_receipts', 'tp_date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tp_receipts', 'tp_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('tp_receipts', 'supplier_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('tp_receipts', 'tp_number',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###
