"""stage 3 domain models

Revision ID: 90a8a82abee0
Revises: c88720d8eba9
Create Date: 2026-06-18 05:36:28.553223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '90a8a82abee0'
down_revision: Union[str, Sequence[str], None] = 'c88720d8eba9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.Enum('IMFL', 'MML', 'CL', 'WINE', 'BEER', name='productcategory'), nullable=False),
    sa.Column('size_ml', sa.Integer(), nullable=False),
    sa.Column('mrp', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('scm_code', sa.String(length=50), nullable=False),
    sa.Column('case_size', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='productstatus'), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'name', 'size_ml', name='uq_business_name_size'),
    sa.UniqueConstraint('business_id', 'scm_code', name='uq_business_scm_code')
    )
    op.create_index(op.f('ix_products_business_id'), 'products', ['business_id'], unique=False)
    op.create_table('barcodes',
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('barcode_value', sa.String(length=100), nullable=False),
    sa.Column('barcode_format', sa.Enum('EAN13', 'EAN8', 'CODE128', 'QR', name='barcodeformat'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'barcode_value', name='uq_business_barcode_value')
    )
    op.create_index(op.f('ix_barcodes_business_id'), 'barcodes', ['business_id'], unique=False)
    op.create_table('tp_receipts',
    sa.Column('tp_number', sa.String(length=100), nullable=False),
    sa.Column('supplier_name', sa.String(length=255), nullable=False),
    sa.Column('tp_date', sa.Date(), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('ocr_raw_text', sa.Text(), nullable=True),
    sa.Column('extracted_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('PROCESSING', 'DRAFT', 'APPROVED', 'REJECTED', name='tpstatus'), nullable=False),
    sa.Column('processed_by', sa.Uuid(), nullable=False),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['processed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tp_receipts_business_id'), 'tp_receipts', ['business_id'], unique=False)
    op.create_table('unknown_barcodes',
    sa.Column('barcode_value', sa.String(length=100), nullable=False),
    sa.Column('scanned_by', sa.Uuid(), nullable=False),
    sa.Column('scanned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'MAPPED', 'IGNORED', name='unknownbarcodestatus'), nullable=False),
    sa.Column('mapped_product_id', sa.Uuid(), nullable=True),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mapped_product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['scanned_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unknown_barcodes_business_id'), 'unknown_barcodes', ['business_id'], unique=False)
    op.create_table('mrp_change_requests',
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('tp_receipt_id', sa.Uuid(), nullable=False),
    sa.Column('old_mrp', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('new_mrp', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='mrpchangestatus'), nullable=False),
    sa.Column('decided_by', sa.Uuid(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['tp_receipt_id'], ['tp_receipts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mrp_change_requests_business_id'), 'mrp_change_requests', ['business_id'], unique=False)
    op.create_table('mrp_history',
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('old_mrp', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('new_mrp', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('change_source', sa.Enum('TP_DETECTION', 'MANUAL', name='mrpchangesource'), nullable=False),
    sa.Column('changed_by', sa.Uuid(), nullable=False),
    sa.Column('tp_receipt_id', sa.Uuid(), nullable=True),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['tp_receipt_id'], ['tp_receipts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mrp_history_business_id'), 'mrp_history', ['business_id'], unique=False)
    op.create_table('stock_movements',
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('movement_type', sa.Enum('OPENING', 'PURCHASE', 'SALE', 'RETURN', 'DAMAGE', 'ADJUSTMENT', name='movementtype'), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('batch_number', sa.String(length=100), nullable=True),
    sa.Column('reference_id', sa.Uuid(), nullable=True),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['reference_id'], ['tp_receipts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_stock_movements_business_date', 'stock_movements', ['business_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_stock_movements_business_id'), 'stock_movements', ['business_id'], unique=False)
    op.create_index('ix_stock_movements_business_product_date', 'stock_movements', ['business_id', 'product_id', 'created_at'], unique=False)
    op.create_index('ix_stock_movements_business_type_date', 'stock_movements', ['business_id', 'movement_type', 'created_at'], unique=False)
    op.create_table('tp_receipt_lines',
    sa.Column('tp_receipt_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=True),
    sa.Column('extracted_name', sa.String(length=255), nullable=False),
    sa.Column('quantity_cases', sa.Integer(), nullable=False),
    sa.Column('quantity_bottles', sa.Integer(), nullable=False),
    sa.Column('total_bottles', sa.Integer(), nullable=False),
    sa.Column('extracted_mrp', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('batch_number', sa.String(length=100), nullable=True),
    sa.Column('match_confidence', sa.Float(), nullable=False),
    sa.Column('is_matched', sa.Boolean(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['tp_receipt_id'], ['tp_receipts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tp_receipt_lines_business_id'), 'tp_receipt_lines', ['business_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tp_receipt_lines_business_id'), table_name='tp_receipt_lines')
    op.drop_table('tp_receipt_lines')
    op.drop_index('ix_stock_movements_business_type_date', table_name='stock_movements')
    op.drop_index('ix_stock_movements_business_product_date', table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_business_id'), table_name='stock_movements')
    op.drop_index('ix_stock_movements_business_date', table_name='stock_movements')
    op.drop_table('stock_movements')
    op.drop_index(op.f('ix_mrp_history_business_id'), table_name='mrp_history')
    op.drop_table('mrp_history')
    op.drop_index(op.f('ix_mrp_change_requests_business_id'), table_name='mrp_change_requests')
    op.drop_table('mrp_change_requests')
    op.drop_index(op.f('ix_unknown_barcodes_business_id'), table_name='unknown_barcodes')
    op.drop_table('unknown_barcodes')
    op.drop_index(op.f('ix_tp_receipts_business_id'), table_name='tp_receipts')
    op.drop_table('tp_receipts')
    op.drop_index(op.f('ix_barcodes_business_id'), table_name='barcodes')
    op.drop_table('barcodes')
    op.drop_index(op.f('ix_products_business_id'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
