"""add purchase price

Revision ID: d0903d1f5f84
Revises: eb9ee2c06818
Create Date: 2026-06-27 04:54:39.837871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0903d1f5f84'
down_revision: Union[str, Sequence[str], None] = 'eb9ee2c06818'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('purchase_price', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'purchase_price')
    # ### end Alembic commands ###
