"""add extracted_scm_code

Revision ID: eb9ee2c06818
Revises: 253b27de811a
Create Date: 2026-06-24 05:11:57.539362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb9ee2c06818'
down_revision: Union[str, Sequence[str], None] = '253b27de811a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tp_receipt_lines', sa.Column('extracted_scm_code', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tp_receipt_lines', 'extracted_scm_code')
    # ### end Alembic commands ###
