"""add additional_scm_codes and remove unique constraint

Revision ID: ef8e5e8036f5
Revises: d0903d1f5f84
Create Date: 2026-06-27 05:46:47.274303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ef8e5e8036f5'
down_revision: Union[str, Sequence[str], None] = 'd0903d1f5f84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('additional_scm_codes', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False))
    op.drop_constraint(op.f('uq_business_scm_code'), 'products', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_business_scm_code'), 'products', ['business_id', 'scm_code'], postgresql_nulls_not_distinct=False)
    op.drop_column('products', 'additional_scm_codes')
    # ### end Alembic commands ###
